FROM archlinux:latest

COPY pacman.conf /etc/pacman.conf
RUN pacman -Syu fish bc curl diffutils findutils less ncurses passwd pinentry procps-ng shadow-utils sudo util-linux vte-profile wget --noconfirm
