FROM library/archlinux

LABEL maintainer="phantomic@protonmail.com"

COPY pacman.conf /etc/pacman.conf

RUN pacman -Syu --needed --noconfirm sudo namcap fakeroot audit grep diffutils findutils 

# dependencies for yay
RUN pacman -S --noconfirm git less ncurses pinentry procps-ng util-linux wget fish bc curl base-devel shadow

