name: Automatically Build Images

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  buildimage:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        variant:         
          - arch-base
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/phantomic12/distrobox:${{ matrix.variant }}
          file: Dockerfile.${{ matrix.variant }}
    
